services:
  arrival:
    build: 
      context: .
      dockerfile: arrival.Dockerfile
    ports:
      - "${PORT:-6767}:5000"
    env_file:
      - .env
    # uncomment for development with hot reload
    # volumes:
    #   - ".:/app" 
    # environment:
    #   - FLASK_ENV=development
    # networks:     # uncomment for gantry ui
    #   - drivethrough-net  
    restart: always

# networks:         # uncomment for gantry ui
#   drivethrough-net:
#     external: true