version: '3.8'

services:
  arrival:
    build: 
      context: .
      dockerfile: arrival.Dockerfile
    ports:
      - "${PORT:-6767}:5000"
    env_file:
      - .env
    volumes:
      - ".:/app" # DELETE ONCE DONE WITH DEVELOPMENT
    environment:
      - FLASK_ENV=development
    restart: always