services:
  consumer:
    build: 
      context: ./consumer
      dockerfile: consumer.Dockerfile
    container_name: rabbit_consumer
    env_file:
      - .env
    environment:
      - CONSUMER_RABBITMQ_URL=${RABBITMQ_URL}
  publisher:
    build: 
      context: ./publisher
      dockerfile: publisher.Dockerfile
    container_name: rabbit_publisher
    ports:
      - "6700:3000"
    restart: always
    env_file:
      - .env
    environment:
      - PUBLISHER_RABBITMQ_URL=${RABBITMQ_URL}